GET http://localhost:5000/
Content-Type: application/json

###
POST http://localhost:5000/new_user_reg
Content-Type: application/json

{
    "password": "password",
    "email": "test2@gamil.com",
    "lang_id": 3
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "password": "password",
    "email": "example@gmail.com"
}

###

GET http://localhost:5000/get_lang_code
Content-Type: application/json

###

POST http://localhost:5000/translate
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MiwibGFuZ19jb2RlIjoiREEifQ.DxNv9Ch6uNV85HL-XYfvXdOsvzjDk8-jVTEApVrKDpQ",
    "text":"This is the official documentation for Python"
}

###

POST http://localhost:5000/history
Content-Type: application/json

{
    "token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibGFuZ19jb2RlIjoiQkcifQ._O-YOFQMUU9ZAj_U_mCucdXHs1gcO3fZTdHePMpRp2g"
}

###

POST http://localhost:5000/translate_with_option
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibGFuZ19jb2RlIjoiQkcifQ._O-YOFQMUU9ZAj_U_mCucdXHs1gcO3fZTdHePMpRp2g",
    "text": "さようなら",
    "to_translate_lang_id": 6
}